---


### Add User

- name: Ensure group "web" exists
  group:
    name: web
    gid: 3001
    state: present

- name: Add the user 'apache' with a specific uid and a primary group of 'web'
  user:
    name: apache
    uid: 3000
    groups: web

- name: Ensure group "was" exists
  group:
    name: was
    gid: 4001
    state: present

- name: Add the user 'tomcat' with a specific uid and a primary group of 'was'
  user:
    name: tomcat
    uid: 4000
    groups: was



### Create Directory

- name: Creates directory '/svc/uplus/web/apache'
  file:
    path: /svc/uplus/web/apache
    state: directory
    owner: apache
    group: apache
    mode: 0775
    force: yes

- name: Creates directory 'logs-apache'
  file:
    path: /logs/uplus/web/apache
    state: directory
    owner: apache
    group: web
    mode: 0775
    force: yes

- name: Creates directory '/svc/uplus/was/tomcat'
  file:
    path: /svc/uplus/was/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0775
    force: yes

- name: Creates directory 'logs-tomcat'
  file:
    path: /logs/uplus/was/tomcat
    state: directory
    owner: tomcat
    group: was
    mode: 0775
    force: yes


