---


### Add User

- name: Ensure group "web" exists
  group:
    name: web
    state: present
    gid: 3000

- name: Add the user 'apache' with a specific uid and a primary group of 'web'
  user:
    name: apache
    uid: 3000
    groups: web,apache

- name: Ensure group "was" exists
  group:
    name: was
    state: present
    gid: 4000

- name: Add the user 'tomcat' with a specific uid and a primary group of 'was'
  user:
    name: tomcat
    uid: 4000
    groups: was,tomcat



### Create Directory

- name: Creates directory '/svc/uplus/web/apache'
  file:
    path: /svc/uplus/web/apache
    state: directory
    owner: apache
    group: apache
    mode: 0775

- name: Creates directory 'logs-apache'
  file:
    path: /logs/uplus/web/apache
    state: directory
    owner: apache
    group: web
    mode: 0775

- name: Creates directory '/svc/uplus/was/tomcat'
  file:
    path: /svc/uplus/was/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0775

- name: Creates directory 'logs-tomcat'
  file:
    path: /logs/uplus/was/tomcat
    state: directory
    owner: tomcat
    group: was
    mode: 0775


### download apache & tomcat-connector

### extract a & t

### compile a & t

### configure setting

### create script
