---


### Add User

- name: Ensure group "web" exists
  group:
    name: web
    gid: 3001
    state: present

- name: Add the user 'apache' with a specific uid and a primary group of 'web'
  user:
    name: apache
    uid: 3000
    groups: web

- name: Ensure group "was" exists
  group:
    name: was
    gid: 4001
    state: present

- name: Add the user 'tomcat' with a specific uid and a primary group of 'was'
  user:
    name: tomcat
    uid: 4000
    groups: was



### Create Directory

- name: Creates directory  "{{base_install_dir}}"
  file:
    path: "{{base_install_dir}}"
    state: directory
    owner: root
    group: root
    mode: 0775
    force: yes

- name: Creates directory "{{base_log_dir}}"
  file:
    path: "{{base_log_dir}}"
    state: directory
    owner: root
    group: root
    mode: 0775
    force: yes

- name: Creates directory '{{apache_install_dir}}"
  file:
    path: "{{apache_install_dir}}"
    state: directory
    owner: apache
    group: apache
    mode: 0775
    force: yes

- name: Creates directory "{{apache_log_dir}}"
  file:
    path: "{{apache_log_dir}}"
    state: directory
    owner: apache
    group: web
    mode: 0775
    force: yes

- name: Creates directory "{{tomcat_install_dir}}"
  file:
    path: "{{tomcat_install_dir}}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0775
    force: yes

- name: Creates directory "{{tomcat_log_dir}}"
  file:
    path: "{{tomcat_log_dir}}"
    state: directory
    owner: tomcat
    group: was
    mode: 0775
    force: yes


