---

### config


- name: Apache config
  command:

- httpd.conf
- extra/httpd-ssl.conf
- extra/httpd-vhosts.conf
- extra/httpd-mpm.conf

- name: Tomcat-connetor config
- mod-jk.conf
- urifdlfdllf
- workers.property


- name: Tomcat config

- start.sh
- stop.sh
- server.xml
- web.xml


- name: Compile PCRE
  command: "{{ item }} chdir={{download_dir}}/{{pcre_version}}/"
  with_items:
    - ./configure --prefix=/usr/local/pcre
    - /usr/bin/make
    - /usr/bin/make install

- name: Compile Apache
  command: "{{ item }} chdir={{download_dir}}/{{apache_version}}/"
  with_items:
    - ./configure --prefix=/svc/uplus/web/apache --enable-so --enable-ssl 
                  --with-mpm=worker --with-apr=/usr/local/apr --with-apr-util=/usr/local/apr-util 
                  --with-pcre=/usr/local/pcre --enable-mpms-shared=all
    - /usr/bin/make
    - /usr/bin/make install


- name: Compile Tomcat-connector
  command: "{{ item }} chdir={{download_dir}}/{{tconnector_version}}-src/native"
  with_items:
    - ./configure --with-apxs=/svc/uplus/web/apache/bin/apxs
    - /usr/bin/make
    - /usr/bin/make install

- name: Compile Tomcat-native
  command: "{{ item }} chdir={{tomcat_install_dir}}/{{tnative_version}}-src/native"
  with_items:
    - ./configure --prefix=/svc/uplus/was/tomcat/nativelib
                  --with-java-home=/svc/uplus/was/jdk1.8.0_202 
                  --with-apr=/usr/local/apr 
                  --with-ssl
    - /usr/bin/make
    - /usr/bin/make install


